first commit

diff --git a/mkrepo b/mkrepo
--- a/mkrepo
+++ b/mkrepo
@@ -6,7 +6,14 @@ loc=${3:-$(pwd)};
 path="$loc/$repo";
 
 echo "creating repo $path for user $user";
-curl -u $user https://api.github.com/user/repos -d '{"name":'\"$repo\"',"private":true}'
+ret=$(curl -u $user https://api.github.com/user/repos -d '{"name":'\"$repo\"',"private":true}')
+echo "$ret"
+echo "$?"
+if [ "$?" -ne 0 ]; then
+	printf "curl failed. exiting."
+	exit 1
+fi
+
 mkdir $path && cd $path
 git init
 touch README.md
